// <auto-generated />
using System;
using Codaxy.Inventory.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Codaxy.Inventory.App.Persistence.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20191217124137_DefineAssetLicenseRelationship")]
    partial class DefineAssetLicenseRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetSubstatusId");

                    b.Property<Guid>("AssetTypeId");

                    b.Property<Guid>("AvailabilityId");

                    b.Property<Guid>("ConfidentialityId");

                    b.Property<string>("Description");

                    b.Property<Guid>("ImportanceId");

                    b.Property<Guid>("IntegrityId");

                    b.Property<Guid>("LocationId");

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("AssetSubstatusId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ConfidentialityId");

                    b.HasIndex("ImportanceId");

                    b.HasIndex("IntegrityId");

                    b.HasIndex("LocationId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AssetCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetStatusId");

                    b.Property<string>("Description");

                    b.Property<string>("Substatus");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Confidentiality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Confidentiality");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Importance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.HasKey("Id");

                    b.ToTable("Importance");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Integrity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Integrity");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.License", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<int>("Available");

                    b.Property<int>("Consumed");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<Guid>("LicenseCategoryId");

                    b.Property<Guid>("LicenseClassId");

                    b.Property<Guid>("LicenseExpirationModelId");

                    b.Property<Guid>("LicenseTypeId");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<Guid>("VendorId");

                    b.HasKey("AssetId");

                    b.HasIndex("LicenseCategoryId");

                    b.HasIndex("LicenseClassId");

                    b.HasIndex("LicenseExpirationModelId");

                    b.HasIndex("LicenseTypeId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseExpirationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseExpirationModel");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Description");

                    b.Property<string>("Floor");

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Room");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Vendors.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email");

                    b.Property<Guid>("LocationId");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("RegistrationNumber");

                    b.Property<decimal>("VATNumber");

                    b.Property<string>("Web");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Asset", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", "AssetSubstatus")
                        .WithMany()
                        .HasForeignKey("AssetSubstatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Confidentiality", "Confidentiality")
                        .WithMany()
                        .HasForeignKey("ConfidentialityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Importance", "Importance")
                        .WithMany()
                        .HasForeignKey("ImportanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Integrity", "Integrity")
                        .WithMany()
                        .HasForeignKey("IntegrityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Location", "Location")
                        .WithMany("Asset")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetStatus", "AssetStatus")
                        .WithMany("AssetSubstatus")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetCategory")
                        .WithMany("AssetType")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.License", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("License")
                        .HasForeignKey("Codaxy.Inventory.App.Licenses.Licenses.License", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseCategory", "LicenseCategory")
                        .WithMany()
                        .HasForeignKey("LicenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseClass", "LicenseClass")
                        .WithMany()
                        .HasForeignKey("LicenseClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseExpirationModel", "LicenseExpirationModel")
                        .WithMany()
                        .HasForeignKey("LicenseExpirationModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Vendors.Vendor", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
