// <auto-generated />
using System;
using Codaxy.Inventory.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Codaxy.Inventory.App.Persistence.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20191216090811_AddAssetStatusAndSubstatus")]
    partial class AddAssetStatusAndSubstatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AssetCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fb2eccb-c940-48f9-aac6-0a204cdce42e"),
                            Name = "Entities"
                        },
                        new
                        {
                            Id = new Guid("a9871483-5d51-4134-9a38-425de55acdba"),
                            Name = "Information"
                        },
                        new
                        {
                            Id = new Guid("20e2cb55-bb14-4fb9-9455-12ef169d24e6"),
                            Name = "Software"
                        },
                        new
                        {
                            Id = new Guid("e1bbabd5-5bc8-424b-bf14-687c912e1d5b"),
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = new Guid("5653b18d-2036-4f2a-a54d-1efa8db6ec85"),
                            Name = "Services"
                        },
                        new
                        {
                            Id = new Guid("6c993228-80e4-45eb-baf6-877310986aca"),
                            Name = "Premises"
                        },
                        new
                        {
                            Id = new Guid("b99d0b01-d36e-4b43-ad52-89fbf05b26f3"),
                            Name = "Transportation"
                        });
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetStatusId");

                    b.Property<string>("Description");

                    b.Property<string>("Substatus");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetStatus", "AssetStatus")
                        .WithMany("AssetSubstatus")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetCategory")
                        .WithMany("AssetType")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
