// <auto-generated />
using System;
using Codaxy.Inventory.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Codaxy.Inventory.App.Persistence.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20201005074544_UpdateVendorTable")]
    partial class UpdateVendorTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Activations.Activation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActivationDate");

                    b.Property<Guid?>("AssetId");

                    b.Property<DateTime?>("DeactivationDate");

                    b.Property<Guid?>("PersonId");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("VolumeId");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VolumeId");

                    b.ToTable("Activation");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AssetSubstatusId");

                    b.Property<Guid>("AssetTypeId");

                    b.Property<Guid?>("AvailabilityId");

                    b.Property<Guid?>("BusinessEntityId");

                    b.Property<Guid?>("ConfidentialityId");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<Guid?>("ImportanceId");

                    b.Property<bool>("Incomplete");

                    b.Property<Guid?>("IntegrityId");

                    b.Property<int?>("InventoryNumber");

                    b.Property<string>("InvoiceNumber");

                    b.Property<Guid?>("LocationId");

                    b.Property<string>("Name")
                        .HasMaxLength(300);

                    b.Property<Guid>("PersonId");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("URL")
                        .HasMaxLength(500);

                    b.Property<Guid>("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("AssetSubstatusId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("BusinessEntityId");

                    b.HasIndex("ConfidentialityId");

                    b.HasIndex("ImportanceId");

                    b.HasIndex("IntegrityId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VendorId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("AssetCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetStatusId");

                    b.Property<string>("Description");

                    b.Property<string>("Substatus");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.BusinessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("BusinessEntity");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.BusinessUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("BusinessUnit");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryCode");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Clouds.Cloud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ManagementURL");

                    b.Property<string>("Name");

                    b.Property<Guid>("VolumeId");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.ToTable("Cloud");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipment", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid>("CommunicationEquipmentCategoryId");

                    b.Property<Guid>("CommunicationEquipmentClassId");

                    b.Property<Guid?>("ManufacturerId");

                    b.Property<DateTime?>("ManufacturingDate");

                    b.Property<string>("Model");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime?>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("CommunicationEquipmentCategoryId");

                    b.HasIndex("CommunicationEquipmentClassId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("CommunicationEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CommunicationEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipmentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CommunicationEquipmentClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipment", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid>("ComputerEquipmentCategoryId");

                    b.Property<Guid?>("ManufacturerId");

                    b.Property<DateTime?>("ManufacturingDate");

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid?>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime?>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("ComputerEquipmentCategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("ComputerEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ComputerEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Confidentiality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Confidentiality");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Country", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Code");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.DataStorage", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<string>("Capacity");

                    b.Property<Guid>("DataStorageCategoryId");

                    b.Property<bool>("IsEncrypted");

                    b.Property<bool>("IsPersonalData");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<DateTime>("ManufacturingDate");

                    b.Property<string>("Model");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("DataStorageCategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("DataStorage");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.DataStorageCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("DataStorageCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid?>("ElectronicDeviceTypeId");

                    b.Property<DateTime?>("GuaranteeExpirationDate");

                    b.Property<string>("GuaranteeNumber");

                    b.Property<Guid?>("ManufacturerId");

                    b.Property<DateTime?>("ManufacturingDate");

                    b.Property<string>("Model");

                    b.Property<string>("SerialNumber");

                    b.HasKey("AssetId");

                    b.HasIndex("ElectronicDeviceTypeId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("ElectronicDevice");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Tags.ElectronicDeviceTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ElectronicDeviceTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ElectronicDeviceType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceTypeElectronicDeviceTag", b =>
                {
                    b.Property<Guid>("ElectronicDeviceTypeId");

                    b.Property<Guid>("ElectronicDeviceTagId");

                    b.HasKey("ElectronicDeviceTypeId", "ElectronicDeviceTagId");

                    b.HasIndex("ElectronicDeviceTagId");

                    b.ToTable("ElectronicDeviceTypeElectronicDeviceTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("EventCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EventData");

                    b.Property<Guid>("EventTypeId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<Guid>("EventCategoryId");

                    b.Property<string>("Type")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("EventCategoryId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Furnitures.Items.Furniture", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid?>("FurnitureTypeId");

                    b.Property<string>("Model");

                    b.HasKey("AssetId");

                    b.HasIndex("FurnitureTypeId");

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Furnitures.Types.FurnitureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FurnitureType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Importance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Importance");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.Information", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessRights");

                    b.Property<string>("Author");

                    b.Property<Guid?>("AvailabilityId");

                    b.Property<bool?>("ClientsPersonalInformation");

                    b.Property<Guid?>("ConfidentialityId");

                    b.Property<string>("Description");

                    b.Property<Guid?>("ImportanceId");

                    b.Property<bool?>("Incomplete");

                    b.Property<Guid>("InformationTypeId");

                    b.Property<Guid?>("IntegrityId");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<Guid>("PersonId");

                    b.Property<bool?>("PersonalInformation");

                    b.Property<Guid?>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ConfidentialityId");

                    b.HasIndex("ImportanceId");

                    b.HasIndex("InformationTypeId");

                    b.HasIndex("IntegrityId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Information");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.InformationLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CloudId");

                    b.Property<Guid?>("ElectronicDeviceId");

                    b.Property<Guid>("InformationId");

                    b.Property<Guid?>("PhysicalLocationId");

                    b.Property<Guid?>("SoftwareId");

                    b.Property<string>("URL");

                    b.Property<Guid?>("VirtualMachineId");

                    b.HasKey("Id");

                    b.HasIndex("CloudId");

                    b.HasIndex("ElectronicDeviceId");

                    b.HasIndex("InformationId");

                    b.HasIndex("PhysicalLocationId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("VirtualMachineId");

                    b.ToTable("InformationLocation");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Tags.InformationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InformationTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Tags.InformationTagInformation", b =>
                {
                    b.Property<Guid>("InformationId");

                    b.Property<Guid>("InformationTagId");

                    b.HasKey("InformationId", "InformationTagId");

                    b.HasIndex("InformationTagId");

                    b.ToTable("InformationTagInformation");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Types.InformationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InformationType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Integrity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Integrity");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.License", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<bool?>("AutoRenew");

                    b.Property<Guid?>("CurrencyId");

                    b.Property<string>("KeyIdentifier");

                    b.Property<Guid?>("LicenseExpirationModelId");

                    b.Property<Guid?>("LicenseModelId");

                    b.Property<Guid?>("LicenseTypeId");

                    b.Property<string>("ManagementConsoleUrl");

                    b.Property<Guid?>("PeriodId");

                    b.Property<string>("RegistrationNumber");

                    b.Property<DateTime?>("SubscriptionExpirationDate");

                    b.Property<decimal?>("SubscriptionFee");

                    b.HasKey("AssetId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LicenseExpirationModelId");

                    b.HasIndex("LicenseModelId");

                    b.HasIndex("LicenseTypeId");

                    b.HasIndex("PeriodId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("LicenseCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("LicenseClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseExpirationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("LicenseExpirationModel");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("LicenseModel");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("LicenseType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ChangeDate");

                    b.Property<int>("ChangedBy");

                    b.Property<Guid>("ChildAssetId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<Guid>("LinkStatusId");

                    b.Property<Guid>("LinkTypeId");

                    b.Property<Guid>("ParentAssetId");

                    b.HasKey("Id");

                    b.HasIndex("ChildAssetId");

                    b.HasIndex("LinkStatusId");

                    b.HasIndex("LinkTypeId");

                    b.HasIndex("ParentAssetId");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("LinkCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Status")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("LinkStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<string>("InverseLinkName")
                        .HasMaxLength(30);

                    b.Property<Guid>("LinkCategoryId");

                    b.Property<string>("LinkName")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("LinkCategoryId");

                    b.ToTable("LinkType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CityId");

                    b.Property<string>("CountryCode");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<int?>("Floor");

                    b.Property<int?>("HouseNumber");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8);

                    b.Property<string>("Room")
                        .HasMaxLength(30);

                    b.Property<Guid?>("StateId");

                    b.Property<string>("Street")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("StateId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.MaintenanceContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AssetId");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("ContractNumber");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<Guid?>("MaintenanceTypeId");

                    b.Property<DateTime?>("ServiceDueDate");

                    b.Property<Guid>("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("MaintenanceTypeId");

                    b.HasIndex("VendorId");

                    b.ToTable("MaintenanceContract");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.MaintenanceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDevice", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid?>("ManufacturerId");

                    b.Property<DateTime?>("ManufacturingDate");

                    b.Property<Guid>("MobileDeviceCategoryId");

                    b.Property<string>("Model");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime?>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MobileDeviceCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("MobileDevice");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDeviceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MobileDeviceCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("Period");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientId");

                    b.Property<string>("Name");

                    b.Property<Guid>("ProjectOwnerId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectOwnerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Committee");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("FindingURL")
                        .HasMaxLength(100);

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("PersonId");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ReviewLog", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AssetId");

                    b.Property<string>("Description");

                    b.Property<Guid>("ReviewStatusId");

                    b.HasKey("Id", "AssetId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ReviewStatusId");

                    b.ToTable("ReviewLog");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ReviewStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<string>("Status")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("ReviewStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Sequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AssetInventoryNumber")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(100000);

                    b.HasKey("Id");

                    b.ToTable("Sequence");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Softwares.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("VolumeId");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ManufacturerId");

                    b.Property<string>("Name");

                    b.Property<Guid>("SoftwareOrServiceCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SoftwareOrServiceCategoryId");

                    b.ToTable("SoftwareOrService");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SoftwareOrServiceCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryCode");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.TechnicalEquipment", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<DateTime?>("ManufacturingDate");

                    b.Property<string>("Model");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("TechnicalEquipmentCategoryId");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime?>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TechnicalEquipmentCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("TechnicalEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.TechnicalEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TechnicalEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Vendors.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email");

                    b.Property<string>("Location");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("RegistrationNumber");

                    b.Property<string>("VATNumber");

                    b.Property<string>("Web");

                    b.HasKey("Id");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.VirtualMachines.VirtualMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IPAddress");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VirtualMachine");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Volumes.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("LicenseId");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("SoftwareOrServiceId");

                    b.Property<int>("VolumeTypeId");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("SoftwareOrServiceId");

                    b.HasIndex("VolumeTypeId");

                    b.ToTable("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Volumes.VolumeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("VolumeType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Activations.Activation", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.Volume", "Volume")
                        .WithMany("Activations")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Asset", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", "AssetSubstatus")
                        .WithMany()
                        .HasForeignKey("AssetSubstatusId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Availability", "Availability")
                        .WithMany("Asset")
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.BusinessEntity", "BusinessEntity")
                        .WithMany()
                        .HasForeignKey("BusinessEntityId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Confidentiality", "Confidentiality")
                        .WithMany("Asset")
                        .HasForeignKey("ConfidentialityId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Importance", "Importance")
                        .WithMany("Asset")
                        .HasForeignKey("ImportanceId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Integrity", "Integrity")
                        .WithMany("Asset")
                        .HasForeignKey("IntegrityId");

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Location", "Location")
                        .WithMany("Asset")
                        .HasForeignKey("LocationId");

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetStatus", "AssetStatus")
                        .WithMany("AssetSubstatus")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetCategory", "AssetCategory")
                        .WithMany("AssetType")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.City", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Clouds.Cloud", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.Volume", "Volume")
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("CommunicationEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.CommunicationEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.CommunicationEquipmentCategory", "CommunicationEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("CommunicationEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.CommunicationEquipmentClass", "CommunicationEquipmentClass")
                        .WithMany()
                        .HasForeignKey("CommunicationEquipmentClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("ComputerEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.ComputerEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.ComputerEquipmentCategory", "ComputerEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("ComputerEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.DataStorage", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("DataStorage")
                        .HasForeignKey("Codaxy.Inventory.Entities.DataStorage", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.DataStorageCategory", "DataStorageCategory")
                        .WithMany()
                        .HasForeignKey("DataStorageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("ElectronicDevice")
                        .HasForeignKey("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceType", "ElectronicDeviceType")
                        .WithMany()
                        .HasForeignKey("ElectronicDeviceTypeId");

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceTypeElectronicDeviceTag", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Tags.ElectronicDeviceTag", "ElectronicDeviceTag")
                        .WithMany("Types")
                        .HasForeignKey("ElectronicDeviceTagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceType", "ElectronicDeviceType")
                        .WithMany("Tags")
                        .HasForeignKey("ElectronicDeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventLog", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.EventCategory", "EventCategory")
                        .WithMany()
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Furnitures.Items.Furniture", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("Furniture")
                        .HasForeignKey("Codaxy.Inventory.App.Furnitures.Items.Furniture", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Furnitures.Types.FurnitureType", "FurnitureType")
                        .WithMany()
                        .HasForeignKey("FurnitureTypeId");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.Information", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Confidentiality", "Confidentiality")
                        .WithMany()
                        .HasForeignKey("ConfidentialityId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Importance", "Importance")
                        .WithMany()
                        .HasForeignKey("ImportanceId");

                    b.HasOne("Codaxy.Inventory.App.Informations.Types.InformationType", "InformationType")
                        .WithMany()
                        .HasForeignKey("InformationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Integrity", "Integrity")
                        .WithMany()
                        .HasForeignKey("IntegrityId");

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.InformationLocation", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Infrastructure.Clouds.Cloud", "Cloud")
                        .WithMany()
                        .HasForeignKey("CloudId");

                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", "ElectronicDevice")
                        .WithMany()
                        .HasForeignKey("ElectronicDeviceId");

                    b.HasOne("Codaxy.Inventory.App.Informations.Items.Information", "Information")
                        .WithMany("InformationLocations")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Location", "PhysicalLocation")
                        .WithMany()
                        .HasForeignKey("PhysicalLocationId");

                    b.HasOne("Codaxy.Inventory.App.Infrastructure.Softwares.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.HasOne("Codaxy.Inventory.App.Infrastructure.VirtualMachines.VirtualMachine", "VirtualMachine")
                        .WithMany()
                        .HasForeignKey("VirtualMachineId");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Tags.InformationTagInformation", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Informations.Items.Information", "Information")
                        .WithMany("Tags")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Informations.Tags.InformationTag", "InformationTag")
                        .WithMany("Informations")
                        .HasForeignKey("InformationTagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.License", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("License")
                        .HasForeignKey("Codaxy.Inventory.App.Licenses.Licenses.License", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseExpirationModel", "LicenseExpirationModel")
                        .WithMany()
                        .HasForeignKey("LicenseExpirationModelId");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseModel", "LicenseModel")
                        .WithMany()
                        .HasForeignKey("LicenseModelId");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeId");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Link", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "ChildAsset")
                        .WithMany("ChildLink")
                        .HasForeignKey("ChildAssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LinkStatus", "LinkStatus")
                        .WithMany()
                        .HasForeignKey("LinkStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LinkType", "LinkType")
                        .WithMany()
                        .HasForeignKey("LinkTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "ParentAsset")
                        .WithMany("ParentLink")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.LinkCategory", "LinkCategory")
                        .WithMany()
                        .HasForeignKey("LinkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Location", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.MaintenanceContract", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithMany("MaintenanceContract")
                        .HasForeignKey("AssetId");

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.MaintenanceType", "MaintenanceType")
                        .WithMany()
                        .HasForeignKey("MaintenanceTypeId");

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDevice", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("MobileDevice")
                        .HasForeignKey("Codaxy.Inventory.Entities.MobileDevice", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("Codaxy.Inventory.Entities.MobileDeviceCategory", "MobileDeviceCategory")
                        .WithMany()
                        .HasForeignKey("MobileDeviceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Projects.Project", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "ProjectOwner")
                        .WithMany()
                        .HasForeignKey("ProjectOwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Review", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ReviewLog", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.ReviewStatus", "ReviewStatus")
                        .WithMany()
                        .HasForeignKey("ReviewStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Softwares.Software", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.Volume", "Volume")
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrService", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrServiceCategory", "SoftwareOrServiceCategory")
                        .WithMany()
                        .HasForeignKey("SoftwareOrServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.State", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.TechnicalEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("TechnicalEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.TechnicalEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.TechnicalEquipmentCategory", "TechnicalEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("TechnicalEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Volumes.Volume", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.License", "License")
                        .WithMany("Volumes")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrService", "SoftwareOrService")
                        .WithMany("Volumes")
                        .HasForeignKey("SoftwareOrServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.VolumeType", "VolumeType")
                        .WithMany()
                        .HasForeignKey("VolumeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
