// <auto-generated />
using System;
using Codaxy.Inventory.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Codaxy.Inventory.App.Persistence.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20260925102332_CalendarDatesToDate")]
    partial class CalendarDatesToDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Activations.Activation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ActivationDate")
                        .HasColumnType("date")
                        .HasColumnName("activation_date");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateOnly?>("DeactivationDate")
                        .HasColumnType("date")
                        .HasColumnName("deactivation_date");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("volume_id");

                    b.HasKey("Id")
                        .HasName("pk_activation");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_activation_asset_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_activation_person_id");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_activation_volume_id");

                    b.ToTable("activation", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetSubstatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_substatus_id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<Guid?>("AvailabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_id");

                    b.Property<Guid?>("BusinessEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_entity_id");

                    b.Property<Guid?>("ConfidentialityId")
                        .HasColumnType("uuid")
                        .HasColumnName("confidentiality_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ImportanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("importance_id");

                    b.Property<bool>("Incomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("incomplete");

                    b.Property<Guid?>("IntegrityId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrity_id");

                    b.Property<int?>("InventoryNumber")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_number");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_value");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_asset");

                    b.HasIndex("AssetSubstatusId")
                        .HasDatabaseName("ix_asset_asset_substatus_id");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("ix_asset_asset_type_id");

                    b.HasIndex("AvailabilityId")
                        .HasDatabaseName("ix_asset_availability_id");

                    b.HasIndex("BusinessEntityId")
                        .HasDatabaseName("ix_asset_business_entity_id");

                    b.HasIndex("ConfidentialityId")
                        .HasDatabaseName("ix_asset_confidentiality_id");

                    b.HasIndex("ImportanceId")
                        .HasDatabaseName("ix_asset_importance_id");

                    b.HasIndex("IntegrityId")
                        .HasDatabaseName("ix_asset_integrity_id");

                    b.HasIndex("InventoryNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_inventory_number");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_asset_location_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_asset_person_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_asset_vendor_id");

                    b.ToTable("asset", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_asset_category");

                    b.ToTable("asset_category", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_asset_status");

                    b.ToTable("asset_status", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_status_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Substatus")
                        .HasColumnType("text")
                        .HasColumnName("substatus");

                    b.HasKey("Id")
                        .HasName("pk_asset_substatus");

                    b.HasIndex("AssetStatusId")
                        .HasDatabaseName("ix_asset_substatus_asset_status_id");

                    b.ToTable("asset_substatus", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_category_id");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_asset_type");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("ix_asset_type_asset_category_id");

                    b.ToTable("asset_type", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Persistence.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("new_values_json");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("old_values_json");

                    b.Property<string>("Table")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("table");

                    b.Property<DateTimeOffset>("TimeCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_created");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_audit_log_email");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_log_entity_id");

                    b.HasIndex("Table", "EntityId")
                        .HasDatabaseName("ix_audit_log_table_entity_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("level");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_availability");

                    b.ToTable("availability", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.BusinessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_business_entity");

                    b.ToTable("business_entity", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_city_country_code");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_client");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Clouds.Cloud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ManagementURL")
                        .HasColumnType("text")
                        .HasColumnName("management_url");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("volume_id");

                    b.HasKey("Id")
                        .HasName("pk_cloud");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_cloud_volume_id");

                    b.ToTable("cloud", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Confidentiality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("level");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_confidentiality");

                    b.ToTable("confidentiality", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_country");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_currency");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("ElectronicDeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("electronic_device_type_id");

                    b.Property<DateOnly?>("GuaranteeExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("guarantee_expiration_date");

                    b.Property<string>("GuaranteeNumber")
                        .HasColumnType("text")
                        .HasColumnName("guarantee_number");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacturing_date");

                    b.Property<string>("ModelCode")
                        .HasColumnType("text")
                        .HasColumnName("model_code");

                    b.Property<string>("ModelName")
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("AssetId")
                        .HasName("pk_electronic_device");

                    b.HasIndex("ElectronicDeviceTypeId")
                        .HasDatabaseName("ix_electronic_device_electronic_device_type_id");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_electronic_device_manufacturer_id");

                    b.ToTable("electronic_device", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Tags.ElectronicDeviceTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_electronic_device_tag");

                    b.ToTable("electronic_device_tag", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HoldLicences")
                        .HasColumnType("boolean")
                        .HasColumnName("hold_licences");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_electronic_device_type");

                    b.ToTable("electronic_device_type", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceTypeElectronicDeviceTag", b =>
                {
                    b.Property<Guid>("ElectronicDeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("electronic_device_type_id");

                    b.Property<Guid>("ElectronicDeviceTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("electronic_device_tag_id");

                    b.HasKey("ElectronicDeviceTypeId", "ElectronicDeviceTagId")
                        .HasName("pk_electronic_device_type_electronic_device_tag");

                    b.HasIndex("ElectronicDeviceTagId")
                        .HasDatabaseName("ix_electronic_device_type_electronic_device_tag_electronic_dev");

                    b.ToTable("electronic_device_type_electronic_device_tag", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Furnitures.Items.Furniture", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("FurnitureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("furniture_type_id");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.HasKey("AssetId")
                        .HasName("pk_furniture");

                    b.HasIndex("FurnitureTypeId")
                        .HasDatabaseName("ix_furniture_furniture_type_id");

                    b.ToTable("furniture", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Furnitures.Types.FurnitureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_furniture_type");

                    b.ToTable("furniture_type", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Importance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("level");

                    b.HasKey("Id")
                        .HasName("pk_importance");

                    b.ToTable("importance", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.Information", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessRights")
                        .HasColumnType("text")
                        .HasColumnName("access_rights");

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<Guid?>("AvailabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_id");

                    b.Property<bool?>("ClientsPersonalInformation")
                        .HasColumnType("boolean")
                        .HasColumnName("clients_personal_information");

                    b.Property<Guid?>("ConfidentialityId")
                        .HasColumnType("uuid")
                        .HasColumnName("confidentiality_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ImportanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("importance_id");

                    b.Property<bool?>("Incomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("incomplete");

                    b.Property<Guid>("InformationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("information_type_id");

                    b.Property<Guid?>("IntegrityId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrity_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<bool?>("PersonalInformation")
                        .HasColumnType("boolean")
                        .HasColumnName("personal_information");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_information");

                    b.HasIndex("AvailabilityId")
                        .HasDatabaseName("ix_information_availability_id");

                    b.HasIndex("ConfidentialityId")
                        .HasDatabaseName("ix_information_confidentiality_id");

                    b.HasIndex("ImportanceId")
                        .HasDatabaseName("ix_information_importance_id");

                    b.HasIndex("InformationTypeId")
                        .HasDatabaseName("ix_information_information_type_id");

                    b.HasIndex("IntegrityId")
                        .HasDatabaseName("ix_information_integrity_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_information_person_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_information_project_id");

                    b.ToTable("information", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.InformationLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CloudId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloud_id");

                    b.Property<Guid?>("ElectronicDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("electronic_device_id");

                    b.Property<Guid>("InformationId")
                        .HasColumnType("uuid")
                        .HasColumnName("information_id");

                    b.Property<Guid?>("PhysicalLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("physical_location_id");

                    b.Property<Guid?>("SoftwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_id");

                    b.Property<string>("URL")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid?>("VirtualMachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("virtual_machine_id");

                    b.HasKey("Id")
                        .HasName("pk_information_location");

                    b.HasIndex("CloudId")
                        .HasDatabaseName("ix_information_location_cloud_id");

                    b.HasIndex("ElectronicDeviceId")
                        .HasDatabaseName("ix_information_location_electronic_device_id");

                    b.HasIndex("InformationId")
                        .HasDatabaseName("ix_information_location_information_id");

                    b.HasIndex("PhysicalLocationId")
                        .HasDatabaseName("ix_information_location_physical_location_id");

                    b.HasIndex("SoftwareId")
                        .HasDatabaseName("ix_information_location_software_id");

                    b.HasIndex("VirtualMachineId")
                        .HasDatabaseName("ix_information_location_virtual_machine_id");

                    b.ToTable("information_location", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Tags.InformationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_information_tag");

                    b.ToTable("information_tag", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Tags.InformationTagInformation", b =>
                {
                    b.Property<Guid>("InformationId")
                        .HasColumnType("uuid")
                        .HasColumnName("information_id");

                    b.Property<Guid>("InformationTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("information_tag_id");

                    b.HasKey("InformationId", "InformationTagId")
                        .HasName("pk_information_tag_information");

                    b.HasIndex("InformationTagId")
                        .HasDatabaseName("ix_information_tag_information_information_tag_id");

                    b.ToTable("information_tag_information", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Types.InformationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_information_type");

                    b.ToTable("information_type", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Integrity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("level");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_integrity");

                    b.ToTable("integrity", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.License", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<bool?>("AutoRenew")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renew");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("KeyIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("key_identifier");

                    b.Property<Guid?>("LicenseExpirationModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_expiration_model_id");

                    b.Property<Guid?>("LicenseModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_model_id");

                    b.Property<Guid?>("LicenseTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_type_id");

                    b.Property<string>("ManagementConsoleUrl")
                        .HasColumnType("text")
                        .HasColumnName("management_console_url");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<DateOnly?>("SubscriptionExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("subscription_expiration_date");

                    b.Property<decimal?>("SubscriptionFee")
                        .HasColumnType("numeric")
                        .HasColumnName("subscription_fee");

                    b.HasKey("AssetId")
                        .HasName("pk_license");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_license_currency_id");

                    b.HasIndex("LicenseExpirationModelId")
                        .HasDatabaseName("ix_license_license_expiration_model_id");

                    b.HasIndex("LicenseModelId")
                        .HasDatabaseName("ix_license_license_model_id");

                    b.HasIndex("LicenseTypeId")
                        .HasDatabaseName("ix_license_license_type_id");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_license_period_id");

                    b.ToTable("license", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_license_category");

                    b.ToTable("license_category", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_license_class");

                    b.ToTable("license_class", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseExpirationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_license_expiration_model");

                    b.ToTable("license_expiration_model", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_license_model");

                    b.ToTable("license_model", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.LicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_license_type");

                    b.ToTable("license_type", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("house_number");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Room")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("room");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_location_city_id");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_location_country_code");

                    b.HasIndex("StateId")
                        .HasDatabaseName("ix_location_state_id");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.MaintenanceContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text")
                        .HasColumnName("contact_number");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("text")
                        .HasColumnName("contract_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<Guid?>("MaintenanceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_type_id");

                    b.Property<DateOnly?>("ServiceDueDate")
                        .HasColumnType("date")
                        .HasColumnName("service_due_date");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_contract");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_maintenance_contract_asset_id");

                    b.HasIndex("MaintenanceTypeId")
                        .HasDatabaseName("ix_maintenance_contract_maintenance_type_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_maintenance_contract_vendor_id");

                    b.ToTable("maintenance_contract", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.MaintenanceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_type");

                    b.ToTable("maintenance_type", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("URL")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer");

                    b.ToTable("manufacturer", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_period");

                    b.ToTable("period", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_owner_id");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_project_client_id");

                    b.HasIndex("ProjectOwnerId")
                        .HasDatabaseName("ix_project_project_owner_id");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Sequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssetInventoryNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100000)
                        .HasColumnName("asset_inventory_number");

                    b.HasKey("Id")
                        .HasName("pk_sequence");

                    b.ToTable("sequence", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Softwares.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("volume_id");

                    b.HasKey("Id")
                        .HasName("pk_software");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_software_volume_id");

                    b.ToTable("software", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SoftwareOrServiceCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_or_service_category_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_software_or_service");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_software_or_service_manufacturer_id");

                    b.HasIndex("SoftwareOrServiceCategoryId")
                        .HasDatabaseName("ix_software_or_service_software_or_service_category_id");

                    b.ToTable("software_or_service", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_software_or_service_category");

                    b.ToTable("software_or_service_category", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_state");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_state_country_code");

                    b.ToTable("state", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Vendors.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<string>("VATNumber")
                        .HasColumnType("text")
                        .HasColumnName("vat_number");

                    b.Property<string>("Web")
                        .HasColumnType("text")
                        .HasColumnName("web");

                    b.HasKey("Id")
                        .HasName("pk_vendor");

                    b.ToTable("vendor", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.VirtualMachines.VirtualMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_virtual_machine");

                    b.ToTable("virtual_machine", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Volumes.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SoftwareOrServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_or_service_id");

                    b.Property<int>("VolumeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("volume_type_id");

                    b.HasKey("Id")
                        .HasName("pk_volume");

                    b.HasIndex("LicenseId")
                        .HasDatabaseName("ix_volume_license_id");

                    b.HasIndex("SoftwareOrServiceId")
                        .HasDatabaseName("ix_volume_software_or_service_id");

                    b.HasIndex("VolumeTypeId")
                        .HasDatabaseName("ix_volume_volume_type_id");

                    b.ToTable("volume", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Volumes.VolumeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_volume_type");

                    b.ToTable("volume_type", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Activations.Activation", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_activation_assets_asset_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .HasConstraintName("fk_activation_persons_person_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.Volume", "Volume")
                        .WithMany("Activations")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activation_volumes_volume_id");

                    b.Navigation("Asset");

                    b.Navigation("Person");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Asset", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", "AssetSubstatus")
                        .WithMany()
                        .HasForeignKey("AssetSubstatusId")
                        .HasConstraintName("fk_asset_asset_substatuses_asset_substatus_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_asset_types_asset_type_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Availability", "Availability")
                        .WithMany("Asset")
                        .HasForeignKey("AvailabilityId")
                        .HasConstraintName("fk_asset_availabilities_availability_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.BusinessEntity", "BusinessEntity")
                        .WithMany()
                        .HasForeignKey("BusinessEntityId")
                        .HasConstraintName("fk_asset_business_entities_business_entity_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Confidentiality", "Confidentiality")
                        .WithMany("Asset")
                        .HasForeignKey("ConfidentialityId")
                        .HasConstraintName("fk_asset_confidentialities_confidentiality_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Importance", "Importance")
                        .WithMany("Asset")
                        .HasForeignKey("ImportanceId")
                        .HasConstraintName("fk_asset_importances_importance_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Integrity", "Integrity")
                        .WithMany("Asset")
                        .HasForeignKey("IntegrityId")
                        .HasConstraintName("fk_asset_integrities_integrity_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Location", "Location")
                        .WithMany("Asset")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_asset_locations_location_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_persons_person_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_vendors_vendor_id");

                    b.Navigation("AssetSubstatus");

                    b.Navigation("AssetType");

                    b.Navigation("Availability");

                    b.Navigation("BusinessEntity");

                    b.Navigation("Confidentiality");

                    b.Navigation("Importance");

                    b.Navigation("Integrity");

                    b.Navigation("Location");

                    b.Navigation("Person");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetSubstatus", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetStatus", "AssetStatus")
                        .WithMany("AssetSubstatus")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_substatus_asset_status_asset_status_id");

                    b.Navigation("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetType", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.AssetCategory", "AssetCategory")
                        .WithMany("AssetType")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_type_asset_category_asset_category_id");

                    b.Navigation("AssetCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.City", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("fk_city_countries_country_code");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Clouds.Cloud", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.Volume", "Volume")
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cloud_volumes_volume_id");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("ElectronicDevice")
                        .HasForeignKey("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_electronic_device_asset_asset_id");

                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceType", "ElectronicDeviceType")
                        .WithMany()
                        .HasForeignKey("ElectronicDeviceTypeId")
                        .HasConstraintName("fk_electronic_device_electronic_device_types_electronic_device");

                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .HasConstraintName("fk_electronic_device_manufacturers_manufacturer_id");

                    b.Navigation("Asset");

                    b.Navigation("ElectronicDeviceType");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceTypeElectronicDeviceTag", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Tags.ElectronicDeviceTag", "ElectronicDeviceTag")
                        .WithMany("Types")
                        .HasForeignKey("ElectronicDeviceTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_electronic_device_type_electronic_device_tag_electronic_dev");

                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceType", "ElectronicDeviceType")
                        .WithMany("Tags")
                        .HasForeignKey("ElectronicDeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_electronic_device_type_electronic_device_tag_electronic_dev1");

                    b.Navigation("ElectronicDeviceTag");

                    b.Navigation("ElectronicDeviceType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Furnitures.Items.Furniture", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("Furniture")
                        .HasForeignKey("Codaxy.Inventory.App.Furnitures.Items.Furniture", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_furniture_asset_asset_id");

                    b.HasOne("Codaxy.Inventory.App.Furnitures.Types.FurnitureType", "FurnitureType")
                        .WithMany()
                        .HasForeignKey("FurnitureTypeId")
                        .HasConstraintName("fk_furniture_furniture_types_furniture_type_id");

                    b.Navigation("Asset");

                    b.Navigation("FurnitureType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.Information", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .HasConstraintName("fk_information_availability_availability_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Confidentiality", "Confidentiality")
                        .WithMany()
                        .HasForeignKey("ConfidentialityId")
                        .HasConstraintName("fk_information_confidentiality_confidentiality_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Importance", "Importance")
                        .WithMany()
                        .HasForeignKey("ImportanceId")
                        .HasConstraintName("fk_information_importance_importance_id");

                    b.HasOne("Codaxy.Inventory.App.Informations.Types.InformationType", "InformationType")
                        .WithMany()
                        .HasForeignKey("InformationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_information_information_types_information_type_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Classification.Integrity", "Integrity")
                        .WithMany()
                        .HasForeignKey("IntegrityId")
                        .HasConstraintName("fk_information_integrities_integrity_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_information_persons_person_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_information_projects_project_id");

                    b.Navigation("Availability");

                    b.Navigation("Confidentiality");

                    b.Navigation("Importance");

                    b.Navigation("InformationType");

                    b.Navigation("Integrity");

                    b.Navigation("Person");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.InformationLocation", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Infrastructure.Clouds.Cloud", "Cloud")
                        .WithMany()
                        .HasForeignKey("CloudId")
                        .HasConstraintName("fk_information_location_cloud_cloud_id");

                    b.HasOne("Codaxy.Inventory.App.ElectronicDevices.Devices.ElectronicDevice", "ElectronicDevice")
                        .WithMany()
                        .HasForeignKey("ElectronicDeviceId")
                        .HasConstraintName("fk_information_location_electronic_device_electronic_device_id");

                    b.HasOne("Codaxy.Inventory.App.Informations.Items.Information", "Information")
                        .WithMany("InformationLocations")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_information_location_information_information_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Location", "PhysicalLocation")
                        .WithMany()
                        .HasForeignKey("PhysicalLocationId")
                        .HasConstraintName("fk_information_location_locations_physical_location_id");

                    b.HasOne("Codaxy.Inventory.App.Infrastructure.Softwares.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .HasConstraintName("fk_information_location_softwares_software_id");

                    b.HasOne("Codaxy.Inventory.App.Infrastructure.VirtualMachines.VirtualMachine", "VirtualMachine")
                        .WithMany()
                        .HasForeignKey("VirtualMachineId")
                        .HasConstraintName("fk_information_location_virtual_machines_virtual_machine_id");

                    b.Navigation("Cloud");

                    b.Navigation("ElectronicDevice");

                    b.Navigation("Information");

                    b.Navigation("PhysicalLocation");

                    b.Navigation("Software");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Tags.InformationTagInformation", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Informations.Items.Information", "Information")
                        .WithMany("Tags")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_information_tag_information_information_information_id");

                    b.HasOne("Codaxy.Inventory.App.Informations.Tags.InformationTag", "InformationTag")
                        .WithMany("Informations")
                        .HasForeignKey("InformationTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_information_tag_information_information_tag_information_tag");

                    b.Navigation("Information");

                    b.Navigation("InformationTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.License", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithOne("License")
                        .HasForeignKey("Codaxy.Inventory.App.Licenses.Licenses.License", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_license_asset_asset_id");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("fk_license_currency_currency_id");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseExpirationModel", "LicenseExpirationModel")
                        .WithMany()
                        .HasForeignKey("LicenseExpirationModelId")
                        .HasConstraintName("fk_license_license_expiration_models_license_expiration_model_");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseModel", "LicenseModel")
                        .WithMany()
                        .HasForeignKey("LicenseModelId")
                        .HasConstraintName("fk_license_license_models_license_model_id");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeId")
                        .HasConstraintName("fk_license_license_types_license_type_id");

                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .HasConstraintName("fk_license_periods_period_id");

                    b.Navigation("Asset");

                    b.Navigation("Currency");

                    b.Navigation("LicenseExpirationModel");

                    b.Navigation("LicenseModel");

                    b.Navigation("LicenseType");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Location", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_location_city_city_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("fk_location_country_country_code");

                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .HasConstraintName("fk_location_states_state_id");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.MaintenanceContract", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.Asset", "Asset")
                        .WithMany("MaintenanceContract")
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_maintenance_contract_asset_asset_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Assets.MaintenanceType", "MaintenanceType")
                        .WithMany()
                        .HasForeignKey("MaintenanceTypeId")
                        .HasConstraintName("fk_maintenance_contract_maintenance_types_maintenance_type_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_contract_vendors_vendor_id");

                    b.Navigation("Asset");

                    b.Navigation("MaintenanceType");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Projects.Project", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_client_client_id");

                    b.HasOne("Codaxy.Inventory.App.Directory.People.Person", "ProjectOwner")
                        .WithMany()
                        .HasForeignKey("ProjectOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_person_project_owner_id");

                    b.Navigation("Client");

                    b.Navigation("ProjectOwner");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Infrastructure.Softwares.Software", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.Volume", "Volume")
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_software_volumes_volume_id");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrService", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_software_or_service_manufacturer_manufacturer_id");

                    b.HasOne("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrServiceCategory", "SoftwareOrServiceCategory")
                        .WithMany()
                        .HasForeignKey("SoftwareOrServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_software_or_service_software_or_service_categories_software");

                    b.Navigation("Manufacturer");

                    b.Navigation("SoftwareOrServiceCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.State", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Directory.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("fk_state_country_country_code");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Volumes.Volume", b =>
                {
                    b.HasOne("Codaxy.Inventory.App.Licenses.Licenses.License", "License")
                        .WithMany("Volumes")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_volume_license_license_id");

                    b.HasOne("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrService", "SoftwareOrService")
                        .WithMany("Volumes")
                        .HasForeignKey("SoftwareOrServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_volume_software_or_service_software_or_service_id");

                    b.HasOne("Codaxy.Inventory.App.Shared.Volumes.VolumeType", "VolumeType")
                        .WithMany()
                        .HasForeignKey("VolumeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_volume_volume_types_volume_type_id");

                    b.Navigation("License");

                    b.Navigation("SoftwareOrService");

                    b.Navigation("VolumeType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.Asset", b =>
                {
                    b.Navigation("ElectronicDevice");

                    b.Navigation("Furniture");

                    b.Navigation("License");

                    b.Navigation("MaintenanceContract");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetCategory", b =>
                {
                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Assets.AssetStatus", b =>
                {
                    b.Navigation("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Availability", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Confidentiality", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Tags.ElectronicDeviceTag", b =>
                {
                    b.Navigation("Types");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.ElectronicDevices.Types.ElectronicDeviceType", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Importance", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Items.Information", b =>
                {
                    b.Navigation("InformationLocations");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Informations.Tags.InformationTag", b =>
                {
                    b.Navigation("Informations");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Classification.Integrity", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.Licenses.License", b =>
                {
                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Directory.Locations.Location", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Licenses.SoftwareServices.SoftwareOrService", b =>
                {
                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Codaxy.Inventory.App.Shared.Volumes.Volume", b =>
                {
                    b.Navigation("Activations");
                });
#pragma warning restore 612, 618
        }
    }
}
