using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Codaxy.Inventory.App.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class SchemaConstraints : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_Asset_InventoryNumber",
                table: "Asset",
                column: "InventoryNumber",
                unique: true
            );

            // The rest is written by hand: these differences exist between the database and the
            // model, not between the model and the snapshot, so EF cannot see them to generate
            // anything. See known-schema-divergence.txt.

            // Defaults left behind by migrations that added a NOT NULL column to a populated table.
            // The model describes none of them, and four name a seeded row that exists in no other
            // database.
            foreach (
                var (table, column) in new[]
                {
                    ("Asset", "BusinessEntityId"),
                    ("Asset", "Incomplete"),
                    ("Asset", "PurchaseDate"),
                    ("Asset", "PurchaseValue"),
                    ("Asset", "VendorId"),
                    ("ElectronicDevice", "ElectronicDeviceTypeId"),
                    ("ElectronicDeviceType", "HoldLicences"),
                    ("Information", "Incomplete"),
                    ("License", "AutoRenew"),
                    ("License", "LicenseModelId"),
                    ("Location", "Floor"),
                    ("Volume", "VolumeTypeId"),
                }
            )
            {
                migrationBuilder.Sql(
                    $"""ALTER TABLE "{table}" ALTER COLUMN "{column}" DROP DEFAULT;"""
                );
            }

            // An AlterColumn with no type left this as text; the model and production both hold
            // character(2). No-op against production, a fix for every database built from scratch.
            migrationBuilder.Sql(
                """ALTER TABLE "Location" ALTER COLUMN "CountryCode" TYPE character(2);"""
            );

            // The model says UseIdentityByDefaultColumn; the database has a serial and a sequence
            // behind it.
            migrationBuilder.Sql(
                """
                ALTER TABLE "VolumeType" ALTER COLUMN "Id" DROP DEFAULT;
                DROP SEQUENCE IF EXISTS "VolumeType_NewId_seq";
                ALTER TABLE "VolumeType" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT setval(
                    pg_get_serial_sequence('"VolumeType"', 'Id'),
                    COALESCE((SELECT max("Id") FROM "VolumeType"), 0) + 1,
                    false);
                """
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(name: "IX_Asset_InventoryNumber", table: "Asset");

            migrationBuilder.Sql(
                """
                ALTER TABLE "VolumeType" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
                CREATE SEQUENCE IF NOT EXISTS "VolumeType_NewId_seq" OWNED BY "VolumeType"."Id";
                SELECT setval(
                    '"VolumeType_NewId_seq"',
                    COALESCE((SELECT max("Id") FROM "VolumeType"), 0) + 1,
                    false);
                ALTER TABLE "VolumeType" ALTER COLUMN "Id"
                    SET DEFAULT nextval('"VolumeType_NewId_seq"');
                """
            );

            migrationBuilder.Sql(
                """ALTER TABLE "Location" ALTER COLUMN "CountryCode" TYPE text;"""
            );

            // The dropped defaults are not restored. Four of them named a row by id, and those ids
            // differ between every database that was seeded separately, so putting them back would
            // write one database's values into another.
        }
    }
}
