// <auto-generated />
using System;
using Codaxy.Inventory.Entities;
using Codaxy.Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Codaxy.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20191216141442_AddAssetAndRelatedTables")]
    partial class AddAssetAndRelatedTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Codaxy.Inventory.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetSubstatusId");

                    b.Property<Guid>("AssetTypeId");

                    b.Property<Guid>("AvailabilityId");

                    b.Property<Guid>("ConfidentialityId");

                    b.Property<string>("Description");

                    b.Property<Guid>("ImportanceId");

                    b.Property<Guid>("IntegrityId");

                    b.Property<Guid>("LocationId");

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("AssetSubstatusId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ConfidentialityId");

                    b.HasIndex("ImportanceId");

                    b.HasIndex("IntegrityId");

                    b.HasIndex("LocationId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AssetCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetSubstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetStatusId");

                    b.Property<string>("Description");

                    b.Property<string>("Substatus");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Confidentiality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Confidentiality");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Importance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.HasKey("Id");

                    b.ToTable("Importance");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Integrity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Level");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Integrity");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Description");

                    b.Property<string>("Floor");

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Room");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Asset", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetSubstatus", "AssetSubstatus")
                        .WithMany()
                        .HasForeignKey("AssetSubstatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Confidentiality", "Confidentiality")
                        .WithMany()
                        .HasForeignKey("ConfidentialityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Importance", "Importance")
                        .WithMany()
                        .HasForeignKey("ImportanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Integrity", "Integrity")
                        .WithMany()
                        .HasForeignKey("IntegrityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Location", "Location")
                        .WithMany("Asset")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetSubstatus", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetStatus", "AssetStatus")
                        .WithMany("AssetSubstatus")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetCategory")
                        .WithMany("AssetType")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
