// <auto-generated />
using System;
using Codaxy.Inventory.Entities;
using Codaxy.Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Codaxy.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20200108084304_AddMobileDeviceTable")]
    partial class AddMobileDeviceTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Codaxy.Inventory.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetSubstatusId");

                    b.Property<Guid>("AssetTypeId");

                    b.Property<Guid?>("AvailabilityId");

                    b.Property<Guid?>("BusinessUnitId");

                    b.Property<Guid?>("CompanyId");

                    b.Property<Guid?>("ConfidentialityId");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<Guid?>("ImportanceId");

                    b.Property<Guid?>("IntegrityId");

                    b.Property<int>("InventoryNumber");

                    b.Property<Guid?>("LocationId");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<Guid?>("PersonId");

                    b.Property<string>("URL")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("AssetSubstatusId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ConfidentialityId");

                    b.HasIndex("ImportanceId");

                    b.HasIndex("IntegrityId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("AssetCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetSubstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetStatusId");

                    b.Property<string>("Description");

                    b.Property<string>("Substatus");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.BusinessUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("BusinessUnit");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryCode");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipment", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid>("CommunicationEquipmentCategoryId");

                    b.Property<Guid>("CommunicationEquipmentClassId");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<DateTime>("ManufacturingDate");

                    b.Property<string>("Model");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("CommunicationEquipmentCategoryId");

                    b.HasIndex("CommunicationEquipmentClassId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("CommunicationEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CommunicationEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipmentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CommunicationEquipmentClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipment", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid>("ComputerEquipmentCategoryId");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<DateTime>("ManufacturingDate");

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("ComputerEquipmentCategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("ComputerEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ComputerEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Confidentiality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Confidentiality");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Code");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("EventCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EventData");

                    b.Property<Guid>("EventTypeId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<Guid>("EventCategoryId");

                    b.Property<string>("Type")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("EventCategoryId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Furniture", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid>("FurnitureCategoryId");

                    b.Property<Guid>("FurnitureClassId");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<DateTime>("ManufacturingDate");

                    b.Property<string>("Model");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("FurnitureCategoryId");

                    b.HasIndex("FurnitureClassId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.FurnitureCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FurnitureCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.FurnitureClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FurnitureClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Importance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Importance");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Integrity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Level")
                        .HasMaxLength(15);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Integrity");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.License", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<int>("Available");

                    b.Property<int>("Consumed");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<Guid>("LicenseCategoryId");

                    b.Property<Guid>("LicenseClassId");

                    b.Property<Guid>("LicenseExpirationModelId");

                    b.Property<Guid>("LicenseTypeId");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<Guid>("VendorId");

                    b.HasKey("AssetId");

                    b.HasIndex("LicenseCategoryId");

                    b.HasIndex("LicenseClassId");

                    b.HasIndex("LicenseExpirationModelId");

                    b.HasIndex("LicenseTypeId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseExpirationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseExpirationModel");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LicenseType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ChangeDate");

                    b.Property<int>("ChangedBy");

                    b.Property<Guid>("ChildAssetId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<Guid>("LinkStatusId");

                    b.Property<Guid>("LinkTypeId");

                    b.Property<Guid>("ParentAssetId");

                    b.HasKey("Id");

                    b.HasIndex("ChildAssetId");

                    b.HasIndex("LinkStatusId");

                    b.HasIndex("LinkTypeId");

                    b.HasIndex("ParentAssetId");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("LinkCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Status")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("LinkStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<string>("InverseLinkName")
                        .HasMaxLength(30);

                    b.Property<Guid>("LinkCategoryId");

                    b.Property<string>("LinkName")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("LinkCategoryId");

                    b.ToTable("LinkType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CityId");

                    b.Property<string>("CountryCode");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<int>("Floor");

                    b.Property<int>("HouseNumber");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8);

                    b.Property<string>("Room")
                        .HasMaxLength(30);

                    b.Property<Guid>("StateId");

                    b.Property<string>("Street")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("StateId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDevice", b =>
                {
                    b.Property<Guid>("AssetId");

                    b.Property<Guid>("ManufacturerId");

                    b.Property<DateTime>("ManufacturingDate");

                    b.Property<Guid>("MobileDeviceCategoryId");

                    b.Property<string>("Model");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("SerialNumber");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("Warranty");

                    b.Property<DateTime>("WarrantyExpirationDate");

                    b.HasKey("AssetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MobileDeviceCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("MobileDevice");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDeviceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MobileDeviceCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryCode");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email");

                    b.Property<Guid>("LocationId");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("RegistrationNumber");

                    b.Property<decimal>("VATNumber");

                    b.Property<string>("Web");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Asset", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetSubstatus", "AssetSubstatus")
                        .WithMany()
                        .HasForeignKey("AssetSubstatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Availability", "Availability")
                        .WithMany("Asset")
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("Codaxy.Inventory.Entities.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("Codaxy.Inventory.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("Codaxy.Inventory.Entities.Confidentiality", "Confidentiality")
                        .WithMany("Asset")
                        .HasForeignKey("ConfidentialityId");

                    b.HasOne("Codaxy.Inventory.Entities.Importance", "Importance")
                        .WithMany("Asset")
                        .HasForeignKey("ImportanceId");

                    b.HasOne("Codaxy.Inventory.Entities.Integrity", "Integrity")
                        .WithMany("Asset")
                        .HasForeignKey("IntegrityId");

                    b.HasOne("Codaxy.Inventory.Entities.Location", "Location")
                        .WithMany("Asset")
                        .HasForeignKey("LocationId");

                    b.HasOne("Codaxy.Inventory.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetSubstatus", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetStatus", "AssetStatus")
                        .WithMany("AssetSubstatus")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetCategory")
                        .WithMany("AssetType")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.City", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("CommunicationEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.CommunicationEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.CommunicationEquipmentCategory", "CommunicationEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("CommunicationEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.CommunicationEquipmentClass", "CommunicationEquipmentClass")
                        .WithMany()
                        .HasForeignKey("CommunicationEquipmentClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("ComputerEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.ComputerEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.ComputerEquipmentCategory", "ComputerEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("ComputerEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventLog", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.EventCategory", "EventCategory")
                        .WithMany()
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Furniture", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("Furniture")
                        .HasForeignKey("Codaxy.Inventory.Entities.Furniture", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.FurnitureCategory", "FurnitureCategory")
                        .WithMany()
                        .HasForeignKey("FurnitureCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.FurnitureClass", "FurnitureClass")
                        .WithMany()
                        .HasForeignKey("FurnitureClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.License", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("License")
                        .HasForeignKey("Codaxy.Inventory.Entities.License", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LicenseCategory", "LicenseCategory")
                        .WithMany()
                        .HasForeignKey("LicenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LicenseClass", "LicenseClass")
                        .WithMany()
                        .HasForeignKey("LicenseClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LicenseExpirationModel", "LicenseExpirationModel")
                        .WithMany()
                        .HasForeignKey("LicenseExpirationModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Link", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "ChildAsset")
                        .WithMany("ChildLink")
                        .HasForeignKey("ChildAssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LinkStatus", "LinkStatus")
                        .WithMany()
                        .HasForeignKey("LinkStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.LinkType", "LinkType")
                        .WithMany()
                        .HasForeignKey("LinkTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Asset", "ParentAsset")
                        .WithMany("ParentLink")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.LinkCategory", "LinkCategory")
                        .WithMany()
                        .HasForeignKey("LinkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Location", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.HasOne("Codaxy.Inventory.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDevice", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("MobileDevice")
                        .HasForeignKey("Codaxy.Inventory.Entities.MobileDevice", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.MobileDeviceCategory", "MobileDeviceCategory")
                        .WithMany()
                        .HasForeignKey("MobileDeviceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.State", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Vendor", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
