// <auto-generated />
using System;
using Codaxy.Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Codaxy.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20260312130633_UpgradeToEfCore10")]
    partial class UpgradeToEfCore10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Codaxy.Inventory.Entities.Activation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VolumeId");

                    b.ToTable("Activation");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetSubstatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfidentialityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ImportanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Incomplete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IntegrityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("InventoryNumber")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetSubstatusId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("BusinessEntityId");

                    b.HasIndex("ConfidentialityId");

                    b.HasIndex("ImportanceId");

                    b.HasIndex("IntegrityId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VendorId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("AssetCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetSubstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Substatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text");

                    b.Property<string>("Table")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("EntityId");

                    b.HasIndex("Table", "EntityId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.BusinessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BusinessEntity");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.BusinessUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BusinessUnit");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Cloud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ManagementURL")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.ToTable("Cloud");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipment", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunicationEquipmentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunicationEquipmentClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warranty")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WarrantyExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("CommunicationEquipmentCategoryId");

                    b.HasIndex("CommunicationEquipmentClassId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("CommunicationEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommunicationEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipmentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommunicationEquipmentClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipment", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComputerEquipmentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warranty")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WarrantyExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("ComputerEquipmentCategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("ComputerEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ComputerEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Confidentiality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Confidentiality");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.DataStorage", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Capacity")
                        .HasColumnType("text");

                    b.Property<Guid>("DataStorageCategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPersonalData")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warranty")
                        .HasColumnType("text");

                    b.Property<DateTime>("WarrantyExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("DataStorageCategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("DataStorage");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.DataStorageCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataStorageCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDevice", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ElectronicDeviceTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuaranteeExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GuaranteeNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModelCode")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.HasKey("AssetId");

                    b.HasIndex("ElectronicDeviceTypeId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("ElectronicDevice");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDeviceTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ElectronicDeviceTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HoldLicences")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ElectronicDeviceType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDeviceTypeElectronicDeviceTag", b =>
                {
                    b.Property<Guid>("ElectronicDeviceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectronicDeviceTagId")
                        .HasColumnType("uuid");

                    b.HasKey("ElectronicDeviceTypeId", "ElectronicDeviceTagId");

                    b.HasIndex("ElectronicDeviceTagId");

                    b.ToTable("ElectronicDeviceTypeElectronicDeviceTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("EventCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventData")
                        .HasColumnType("text");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EventCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EventCategoryId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Furniture", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FurnitureTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.HasKey("AssetId");

                    b.HasIndex("FurnitureTypeId");

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.FurnitureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FurnitureType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Importance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Importance");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Information", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessRights")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<Guid?>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ClientsPersonalInformation")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ConfidentialityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ImportanceId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Incomplete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InformationTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IntegrityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("PersonalInformation")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ConfidentialityId");

                    b.HasIndex("ImportanceId");

                    b.HasIndex("InformationTypeId");

                    b.HasIndex("IntegrityId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Information");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.InformationLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CloudId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ElectronicDeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InformationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhysicalLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SoftwareId")
                        .HasColumnType("uuid");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<Guid?>("VirtualMachineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CloudId");

                    b.HasIndex("ElectronicDeviceId");

                    b.HasIndex("InformationId");

                    b.HasIndex("PhysicalLocationId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("VirtualMachineId");

                    b.ToTable("InformationLocation");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.InformationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InformationTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.InformationTagInformation", b =>
                {
                    b.Property<Guid>("InformationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InformationTagId")
                        .HasColumnType("uuid");

                    b.HasKey("InformationId", "InformationTagId");

                    b.HasIndex("InformationTagId");

                    b.ToTable("InformationTagInformation");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.InformationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InformationType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Integrity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Level")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Integrity");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.License", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyIdentifier")
                        .HasColumnType("text");

                    b.Property<Guid?>("LicenseExpirationModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LicenseModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LicenseTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagementConsoleUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("SubscriptionFee")
                        .HasColumnType("numeric");

                    b.HasKey("AssetId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LicenseExpirationModelId");

                    b.HasIndex("LicenseModelId");

                    b.HasIndex("LicenseTypeId");

                    b.HasIndex("PeriodId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LicenseCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LicenseClass");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseExpirationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LicenseExpirationModel");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LicenseModel");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LicenseType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildAssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("LinkStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LinkTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentAssetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildAssetId");

                    b.HasIndex("LinkStatusId");

                    b.HasIndex("LinkTypeId");

                    b.HasIndex("ParentAssetId");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("LinkCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("LinkStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("InverseLinkName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("LinkCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("LinkCategoryId");

                    b.ToTable("LinkType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Room")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("StateId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MaintenanceContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("MaintenanceTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ServiceDueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("MaintenanceTypeId");

                    b.HasIndex("VendorId");

                    b.ToTable("MaintenanceContract");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MaintenanceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDevice", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MobileDeviceCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warranty")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WarrantyExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MobileDeviceCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("MobileDevice");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDeviceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MobileDeviceCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Period");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectOwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectOwnerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Committee")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FindingURL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id", "AssetId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ReviewStatusId");

                    b.ToTable("ReviewLog");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ReviewStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("ReviewStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Sequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetInventoryNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100000);

                    b.HasKey("Id");

                    b.ToTable("Sequence");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.SoftwareOrService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("SoftwareOrServiceCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SoftwareOrServiceCategoryId");

                    b.ToTable("SoftwareOrService");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.SoftwareOrServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SoftwareOrServiceCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.TechnicalEquipment", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("TechnicalEquipmentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warranty")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WarrantyExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TechnicalEquipmentCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("TechnicalEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.TechnicalEquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TechnicalEquipmentCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("VATNumber")
                        .HasColumnType("text");

                    b.Property<string>("Web")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.VirtualMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VirtualMachine");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SoftwareOrServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("VolumeTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("SoftwareOrServiceId");

                    b.HasIndex("VolumeTypeId");

                    b.ToTable("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.VolumeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VolumeType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Activation", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("Codaxy.Inventory.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("Codaxy.Inventory.Entities.Volume", "Volume")
                        .WithMany("Activations")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Person");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Asset", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetSubstatus", "AssetSubstatus")
                        .WithMany()
                        .HasForeignKey("AssetSubstatusId");

                    b.HasOne("Codaxy.Inventory.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Availability", "Availability")
                        .WithMany("Asset")
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("Codaxy.Inventory.Entities.BusinessEntity", "BusinessEntity")
                        .WithMany()
                        .HasForeignKey("BusinessEntityId");

                    b.HasOne("Codaxy.Inventory.Entities.Confidentiality", "Confidentiality")
                        .WithMany("Asset")
                        .HasForeignKey("ConfidentialityId");

                    b.HasOne("Codaxy.Inventory.Entities.Importance", "Importance")
                        .WithMany("Asset")
                        .HasForeignKey("ImportanceId");

                    b.HasOne("Codaxy.Inventory.Entities.Integrity", "Integrity")
                        .WithMany("Asset")
                        .HasForeignKey("IntegrityId");

                    b.HasOne("Codaxy.Inventory.Entities.Location", "Location")
                        .WithMany("Asset")
                        .HasForeignKey("LocationId");

                    b.HasOne("Codaxy.Inventory.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetSubstatus");

                    b.Navigation("AssetType");

                    b.Navigation("Availability");

                    b.Navigation("BusinessEntity");

                    b.Navigation("Confidentiality");

                    b.Navigation("Importance");

                    b.Navigation("Integrity");

                    b.Navigation("Location");

                    b.Navigation("Person");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetSubstatus", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetStatus", "AssetStatus")
                        .WithMany("AssetSubstatus")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.AssetCategory", "AssetCategory")
                        .WithMany("AssetType")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.City", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Cloud", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Volume", "Volume")
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.CommunicationEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("CommunicationEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.CommunicationEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.CommunicationEquipmentCategory", "CommunicationEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("CommunicationEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.CommunicationEquipmentClass", "CommunicationEquipmentClass")
                        .WithMany()
                        .HasForeignKey("CommunicationEquipmentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("CommunicationEquipmentCategory");

                    b.Navigation("CommunicationEquipmentClass");

                    b.Navigation("Manufacturer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ComputerEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("ComputerEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.ComputerEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.ComputerEquipmentCategory", "ComputerEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("ComputerEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Asset");

                    b.Navigation("ComputerEquipmentCategory");

                    b.Navigation("Manufacturer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.DataStorage", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("DataStorage")
                        .HasForeignKey("Codaxy.Inventory.Entities.DataStorage", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.DataStorageCategory", "DataStorageCategory")
                        .WithMany()
                        .HasForeignKey("DataStorageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("DataStorageCategory");

                    b.Navigation("Manufacturer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDevice", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("ElectronicDevice")
                        .HasForeignKey("Codaxy.Inventory.Entities.ElectronicDevice", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.ElectronicDeviceType", "ElectronicDeviceType")
                        .WithMany()
                        .HasForeignKey("ElectronicDeviceTypeId");

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Asset");

                    b.Navigation("ElectronicDeviceType");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDeviceTypeElectronicDeviceTag", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.ElectronicDeviceTag", "ElectronicDeviceTag")
                        .WithMany("Types")
                        .HasForeignKey("ElectronicDeviceTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.ElectronicDeviceType", "ElectronicDeviceType")
                        .WithMany("Tags")
                        .HasForeignKey("ElectronicDeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectronicDeviceTag");

                    b.Navigation("ElectronicDeviceType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventLog", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("EventType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.EventType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.EventCategory", "EventCategory")
                        .WithMany()
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Furniture", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("Furniture")
                        .HasForeignKey("Codaxy.Inventory.Entities.Furniture", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.FurnitureType", "FurnitureType")
                        .WithMany()
                        .HasForeignKey("FurnitureTypeId");

                    b.Navigation("Asset");

                    b.Navigation("FurnitureType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Information", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("Codaxy.Inventory.Entities.Confidentiality", "Confidentiality")
                        .WithMany()
                        .HasForeignKey("ConfidentialityId");

                    b.HasOne("Codaxy.Inventory.Entities.Importance", "Importance")
                        .WithMany()
                        .HasForeignKey("ImportanceId");

                    b.HasOne("Codaxy.Inventory.Entities.InformationType", "InformationType")
                        .WithMany()
                        .HasForeignKey("InformationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Integrity", "Integrity")
                        .WithMany()
                        .HasForeignKey("IntegrityId");

                    b.HasOne("Codaxy.Inventory.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Availability");

                    b.Navigation("Confidentiality");

                    b.Navigation("Importance");

                    b.Navigation("InformationType");

                    b.Navigation("Integrity");

                    b.Navigation("Person");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.InformationLocation", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Cloud", "Cloud")
                        .WithMany()
                        .HasForeignKey("CloudId");

                    b.HasOne("Codaxy.Inventory.Entities.ElectronicDevice", "ElectronicDevice")
                        .WithMany()
                        .HasForeignKey("ElectronicDeviceId");

                    b.HasOne("Codaxy.Inventory.Entities.Information", "Information")
                        .WithMany("InformationLocations")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Location", "PhysicalLocation")
                        .WithMany()
                        .HasForeignKey("PhysicalLocationId");

                    b.HasOne("Codaxy.Inventory.Entities.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.HasOne("Codaxy.Inventory.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany()
                        .HasForeignKey("VirtualMachineId");

                    b.Navigation("Cloud");

                    b.Navigation("ElectronicDevice");

                    b.Navigation("Information");

                    b.Navigation("PhysicalLocation");

                    b.Navigation("Software");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.InformationTagInformation", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Information", "Information")
                        .WithMany("Tags")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.InformationTag", "InformationTag")
                        .WithMany("Informations")
                        .HasForeignKey("InformationTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Information");

                    b.Navigation("InformationTag");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.License", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("License")
                        .HasForeignKey("Codaxy.Inventory.Entities.License", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Codaxy.Inventory.Entities.LicenseExpirationModel", "LicenseExpirationModel")
                        .WithMany()
                        .HasForeignKey("LicenseExpirationModelId");

                    b.HasOne("Codaxy.Inventory.Entities.LicenseModel", "LicenseModel")
                        .WithMany()
                        .HasForeignKey("LicenseModelId");

                    b.HasOne("Codaxy.Inventory.Entities.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeId");

                    b.HasOne("Codaxy.Inventory.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId");

                    b.Navigation("Asset");

                    b.Navigation("Currency");

                    b.Navigation("LicenseExpirationModel");

                    b.Navigation("LicenseModel");

                    b.Navigation("LicenseType");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Link", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "ChildAsset")
                        .WithMany("ChildLink")
                        .HasForeignKey("ChildAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.LinkStatus", "LinkStatus")
                        .WithMany()
                        .HasForeignKey("LinkStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.LinkType", "LinkType")
                        .WithMany()
                        .HasForeignKey("LinkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Asset", "ParentAsset")
                        .WithMany("ParentLink")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildAsset");

                    b.Navigation("LinkStatus");

                    b.Navigation("LinkType");

                    b.Navigation("ParentAsset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.LinkType", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.LinkCategory", "LinkCategory")
                        .WithMany()
                        .HasForeignKey("LinkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Location", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.HasOne("Codaxy.Inventory.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MaintenanceContract", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithMany("MaintenanceContract")
                        .HasForeignKey("AssetId");

                    b.HasOne("Codaxy.Inventory.Entities.MaintenanceType", "MaintenanceType")
                        .WithMany()
                        .HasForeignKey("MaintenanceTypeId");

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("MaintenanceType");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.MobileDevice", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("MobileDevice")
                        .HasForeignKey("Codaxy.Inventory.Entities.MobileDevice", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("Codaxy.Inventory.Entities.MobileDeviceCategory", "MobileDeviceCategory")
                        .WithMany()
                        .HasForeignKey("MobileDeviceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Manufacturer");

                    b.Navigation("MobileDeviceCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Project", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Person", "ProjectOwner")
                        .WithMany()
                        .HasForeignKey("ProjectOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ProjectOwner");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Review", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ReviewLog", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.ReviewStatus", "ReviewStatus")
                        .WithMany()
                        .HasForeignKey("ReviewStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ReviewStatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Software", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Volume", "Volume")
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.SoftwareOrService", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.SoftwareOrServiceCategory", "SoftwareOrServiceCategory")
                        .WithMany()
                        .HasForeignKey("SoftwareOrServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("SoftwareOrServiceCategory");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.State", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.TechnicalEquipment", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.Asset", "Asset")
                        .WithOne("TechnicalEquipment")
                        .HasForeignKey("Codaxy.Inventory.Entities.TechnicalEquipment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.TechnicalEquipmentCategory", "TechnicalEquipmentCategory")
                        .WithMany()
                        .HasForeignKey("TechnicalEquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Manufacturer");

                    b.Navigation("TechnicalEquipmentCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Volume", b =>
                {
                    b.HasOne("Codaxy.Inventory.Entities.License", "License")
                        .WithMany("Volumes")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.SoftwareOrService", "SoftwareOrService")
                        .WithMany("Volumes")
                        .HasForeignKey("SoftwareOrServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codaxy.Inventory.Entities.VolumeType", "VolumeType")
                        .WithMany()
                        .HasForeignKey("VolumeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");

                    b.Navigation("SoftwareOrService");

                    b.Navigation("VolumeType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Asset", b =>
                {
                    b.Navigation("ChildLink");

                    b.Navigation("CommunicationEquipment");

                    b.Navigation("ComputerEquipment");

                    b.Navigation("DataStorage");

                    b.Navigation("ElectronicDevice");

                    b.Navigation("Furniture");

                    b.Navigation("License");

                    b.Navigation("MaintenanceContract");

                    b.Navigation("MobileDevice");

                    b.Navigation("ParentLink");

                    b.Navigation("TechnicalEquipment");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetCategory", b =>
                {
                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.AssetStatus", b =>
                {
                    b.Navigation("AssetSubstatus");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Availability", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Confidentiality", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDeviceTag", b =>
                {
                    b.Navigation("Types");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.ElectronicDeviceType", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Importance", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Information", b =>
                {
                    b.Navigation("InformationLocations");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.InformationTag", b =>
                {
                    b.Navigation("Informations");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Integrity", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.License", b =>
                {
                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Location", b =>
                {
                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.SoftwareOrService", b =>
                {
                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Codaxy.Inventory.Entities.Volume", b =>
                {
                    b.Navigation("Activations");
                });
#pragma warning restore 612, 618
        }
    }
}
